application: julieyuportfolio
version: 1
runtime: python
api_version: 1

handlers:

- url: /image
  static_dir: image
  

- url: /static
  static_dir: static

- url: /.*
  script: main.py