application: julieyuportfolio
version: 1
runtime: python
api_version: 1

handlers:

- url: /(.*\.(jpg))
  static_files: \1
  upload: (.*\.(jpg))

- url: /static
  static_dir: static

- url: /.*
  script: main.py
